### ISSUE TITLE
No issue,  instead possible modifications.

### ISSUE THREAD

**Issue by drp0** [NitrofMtl/ADC_Sampler#3]
The library is full of excellent ideas and implementation.

I have done a significant re-write to allow repeated readings to be taken.
I have implemented a double column dma array for concurrent sampling.
With accurate micros() timing.

Using 2000 readings from adc0 and adc4 I got: 
- 2 channels captured at  400000 Hz  prescalar 4
- 2 channels captured at  666667 Hz  prescalar 2
- 2 channels captured at  1000000 Hz prescalar 1
- 2 channels captured at ~1908397 Hz prescalar 0 (Impressive! 0.95 MHz for 1 channel )

With 2000 readings from adc0 I got:
- 1 channel  captured at ~1908397 Hz prescalar 0 (Fantastic!  1.91 Mhz for 1 channel)

[ADC_SEQR-drp.zip](https://github.com/NitrofMtl/ADC_Sampler/files/11782499/ADC_SEQR-drp.zip)

I am able to verify the timings by sending the output from a signal generator through the capture system to a pc oscilloscope:
[pc1.zip](https://github.com/NitrofMtl/ADC_Sampler/files/11782508/pc1.zip)

The signal generator was set to 20Khz and a simple low pass filter was used to clean up the signal, prior to adc0.

Do what you want with the code,
David

**Comment by NitrofMtl** [comment]
Hi. 

Thank for the code. Could you make a pull request instead of zip file? Will be much easier to compare the original code.

Regards.

Nitrof

**Comment by drp0** [comment]
Hello,
I have no idea how to create a pull request starting from my zip.
Cheers,
David

**Comment by NitrofMtl** [comment]
[Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)
